# -*- coding: utf-8 -*-
"""Filas_modelagem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y1Gj7G7amqWQ8cmak95Cb8Z4wBxRxGEx
"""

ultimo = 10
preferencia = 0
p=0
fila = list(range(1,ultimo+1))
while True:
  print(f"A fila atual {fila}")
  print("Digite\n<F> para adicionar\n<A> para atender\n<S> Para sair")
  op = input("Digite operação(F,A,S) ").upper()
  if op=="A":
    if len(fila)>0:
      atendido = fila.pop(0)
      print(f"Cliente {atendido} ")
    else:
      print("Fila vazia")
  elif op=="F":
    op2 = input("Qual nivel de preferência(1-alto 2-medio 3-baixo 4-nenhum) ")
    if op2=="1":
      ultimo += 1
      fila.insert(p, ultimo)
      p+=1
    elif op2== "2":
      ultimo += 1
      fila.insert(preferencia, ultimo)
      preferencia+=2
    elif op2== "3":
        ultimo += 1
        fila.insert(int(len(fila)/2),ultimo)
    elif op2=="4":
      ultimo += 1
      fila.append(ultimo)
  elif op=="S":
    break
  else:
    print("Digite operação valida")

#Tratamente de fila com preferência
#1 -Alto é adicionado imediatamante no inicio da fila se vier outro Alto ficara após o que já foi inserido
#2- Medio será adicionado inicio da fila intercalando entre um e um com os outros que já estavam na fila
#3- Baixo será adicionado no meio da fila 
#4- Nenhum será adicionado ao fim da fila normalmente